--CREATE DABASE ON MSSQL SERVER 2022
CREATE DATABASE [BANKING]
GO


--USE DATABASE
USE [BANKING]

--CREATE TABLES
--CREATE TABLE CENTRAL BANK, table name with centrals in plural
CREATE TABLE CENTRALS
(
    id_central SMALLINT PRIMARY KEY IDENTITY(1,1), --sufix central
    name_central NVARCHAR(100) NOT NULL,
    address_central NVARCHAR(100) NOT NULL,
    phone_central NVARCHAR(20) NOT NULL, --required is not nuled and not empty
    email_central NVARCHAR(100) NOT NULL, --required is not nuled and not empty or null
    CREATED_DATE DATETIME NOT NULL, 
    UPDATED_DATE DATETIME NOT NULL --restricted is not nuled and not empty or null
);

--CREATE TABLE BRANCHES
CREATE TABLE BRANCHES
(
    id_branch SMALLINT PRIMARY KEY IDENTITY(1,1),
    code_branch NVARCHAR(10) UNIQUE NOT NULL,
    name_branch NVARCHAR(100) NOT NULL,
    address_branch NVARCHAR(100) NOT NULL,
    phone_branch NVARCHAR(20) NOT NULL,
    email_branch NVARCHAR(100) NOT NULL,
    id_central_branch SMALLINT NOT NULL, --FOREIGN KEY REFERENCES CENTRALS
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
    FOREIGN KEY (id_central_branch) REFERENCES CENTRALS(id_central) --FOREIGN KEY REFERENCES CENTRALS
);

--CREATE TABLE ATMS
CREATE TABLE ATMS
(
    id_atm SMALLINT PRIMARY KEY IDENTITY(1,1),
    code_atm NVARCHAR(10) UNIQUE NOT NULL,
    name_atm NVARCHAR(100) NOT NULL,
    address_atm NVARCHAR(100) NOT NULL,
    phone_atm NVARCHAR(20) NOT NULL,
    email_atm NVARCHAR(100) NOT NULL,
    id_branch_atm SMALLINT NOT NULL, --FOREIGN KEY REFERENCES BRANCHES
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
    FOREIGN KEY (id_branch_atm) REFERENCES BRANCHES(id_branch) --FOREIGN KEY REFERENCES BRANCHES
);

--CREATE TABLE ACCOUNTS HOLDERS
CREATE TABLE ACCOUNTS_HOLDERS
(
    id_account_holder INT PRIMARY KEY IDENTITY(1,1),
    name_account_holder NVARCHAR(100) NOT NULL,
    address_account_holder NVARCHAR(100) NOT NULL,
    phone_account_holder NVARCHAR(20) NOT NULL,
    email_account_holder NVARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_DATE DATETIME NOT NULL
);

-- CREATE TABLE TYPES ACCOUNTS
CREATE TABLE TYPES_ACCOUNTS
(
    id_type_account SMALLINT PRIMARY KEY IDENTITY(1,1),
    name_type_account NVARCHAR(25) NOT NULL,
    status_type_account TINYINT NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_DATE DATETIME NOT NULL
);

-- CREATE TABLE CURRENCYS ACCOUNTS
CREATE TABLE CURRENCY_ACCOUNTS
(
    id_currency_account SMALLINT PRIMARY KEY IDENTITY(1,1),
    name_currency_account NVARCHAR(25) NOT NULL,
    status_currency_account TINYINT NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_DATE DATETIME NOT NULL
);

-- CREATE TABLE TYPES TRANSACTIONS
CREATE TABLE TYPES_TRANSACTIONS
(
    id_type_transaction SMALLINT PRIMARY KEY IDENTITY(1,1),
    name_type_transaction NVARCHAR(25) NOT NULL,
    status_type_transaction TINYINT NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_DATE DATETIME NOT NULL
);

--CREATE TABLE ACCOUNTS
CREATE TABLE ACCOUNTS
(
    id_account INT PRIMARY KEY IDENTITY(1,1),
    number_account NVARCHAR(10) UNIQUE NOT NULL,
    id_account_type_account SMALLINT NOT NULL,
    id_account_currency_account SMALLINT NOT NULL,
    balance_account DECIMAL(18,2) DEFAULT 0.00 NOT NULL,
    id_account_holder_account INT NOT NULL, --FOREIGN KEY REFERENCES ACCOUNTS HOLDERS
    id_account_branch SMALLINT NOT NULL, --FOREIGN KEY REFERENCES BRANCHES
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
    FOREIGN KEY (id_account_type_account) REFERENCES TYPES_ACCOUNTS (id_type_account),
    FOREIGN KEY (id_account_currency_account) REFERENCES CURRENCY_ACCOUNTS (id_currency_account),
    FOREIGN KEY (id_account_holder_account) REFERENCES ACCOUNTS_HOLDERS(id_account_holder), --FOREIGN KEY REFERENCES ACCOUNTS HOLDERS
    FOREIGN KEY (id_account_branch) REFERENCES BRANCHES(id_branch) --FOREIGN KEY REFERENCES BRANCHES
);

--CREATE TABLE TRANSACTIONS
CREATE TABLE TRANSACTIONS
(
    id_transaction INT PRIMARY KEY IDENTITY(1,1),
    id_transaction_type_transaction SMALLINT NOT NULL,
    amount_transaction DECIMAL(18,2) DEFAULT 0.00 NOT NULL,
    id_account_transaction INT NOT NULL, --FOREIGN KEY REFERENCES ACCOUNTS
    id_atm_transaction SMALLINT NOT NULL, --FOREIGN KEY REFERENCES ATMS
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
    FOREIGN KEY (id_transaction_type_transaction) REFERENCES TYPES_TRANSACTIONS(id_type_transaction),
    FOREIGN KEY (id_account_transaction) REFERENCES ACCOUNTS(id_account), --FOREIGN KEY REFERENCES ACCOUNTS
    FOREIGN KEY (id_atm_transaction) REFERENCES ATMS(id_atm) --FOREIGN KEY REFERENCES ATMS
);